spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://%:3306/sys?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Rorwlvm!
  thymeleaf:
    cache: false

  jpa:
    database: mysql
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true